// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/plan/v1/genesis.proto (package lorenzo.plan.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Params } from "./params_pb.js";
import type { Plan } from "./plan_pb.js";

/**
 * GenesisState defines the agent module's genesis state.
 *
 * @generated from message lorenzo.plan.v1.GenesisState
 */
export declare class GenesisState extends Message<GenesisState> {
  /**
   * params defines all the parameters of the module.
   *
   * @generated from field: lorenzo.plan.v1.Params params = 1;
   */
  params?: Params;

  /**
   * next_number is the next auto-increasing plan id
   *
   * @generated from field: uint64 next_number = 2;
   */
  nextNumber: bigint;

  /**
   * plans are the plans
   *
   * @generated from field: repeated lorenzo.plan.v1.Plan plans = 3;
   */
  plans: Plan[];

  constructor(data?: PartialMessage<GenesisState>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.plan.v1.GenesisState";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState;

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean;
}

