// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/plan/v1/params.proto (package lorenzo.plan.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Params defines the parameters for the module.
 *
 * @generated from message lorenzo.plan.v1.Params
 */
export const Params = proto3.makeMessageType(
  "lorenzo.plan.v1.Params",
  () => [
    { no: 1, name: "beacon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "allow_list", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

