// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/plan/v1/plan.proto (package lorenzo.plan.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum lorenzo.plan.v1.PlanStatus
 */
export const PlanStatus = proto3.makeEnum(
  "lorenzo.plan.v1.PlanStatus",
  [
    {no: 0, name: "Pause"},
    {no: 1, name: "Unpause"},
  ],
);

/**
 * Plan defines the details of a project
 *
 * @generated from message lorenzo.plan.v1.Plan
 */
export const Plan = proto3.makeMessageType(
  "lorenzo.plan.v1.Plan",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "plan_desc_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "agent_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "plan_start_time", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "period_time", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "yat_contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "enabled", kind: "enum", T: proto3.getEnumType(PlanStatus) },
  ],
);

