// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/plan/v1/tx.proto (package lorenzo.plan.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { PlanStatus } from "./plan_pb.js";

/**
 * MsgUpdateParams is the request type for the Msg/UpdateParams RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgUpdateParams
 */
export const MsgUpdateParams = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgUpdateParams",
  () => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "params", kind: "message", T: Params },
  ],
);

/**
 * MsgUpdateParamsResponse is the response type for the Msg/UpdateParams RPC
 * method.
 *
 * @generated from message lorenzo.plan.v1.MsgUpdateParamsResponse
 */
export const MsgUpdateParamsResponse = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgUpdateParamsResponse",
  [],
);

/**
 * MsgUpgradePlan is the request type for the Msg/UpgradePlan RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgUpgradePlan
 */
export const MsgUpgradePlan = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgUpgradePlan",
  () => [
    { no: 1, name: "implementation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgUpgradeYATResponse is the response type for the Msg/UpgradeYAT RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgUpgradePlanResponse
 */
export const MsgUpgradePlanResponse = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgUpgradePlanResponse",
  [],
);

/**
 * MsgCreatePlan is the request type for the Msg/CreatePlan RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgCreatePlan
 */
export const MsgCreatePlan = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgCreatePlan",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "plan_desc_uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "agent_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "plan_start_time", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "period_time", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "yat_contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgCreatePlanResponse is the response type for the Msg/CreatePlan RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgCreatePlanResponse
 */
export const MsgCreatePlanResponse = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgCreatePlanResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * MsgSetMerkleRoot is the request type for the Msg/SetMerkleRoot RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgSetMerkleRoot
 */
export const MsgSetMerkleRoot = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgSetMerkleRoot",
  () => [
    { no: 1, name: "plan_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "round_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "merkle_root", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgSetMerkleRootResponse is the response type for the Msg/SetMerkleRoot RPC
 * method.
 *
 * @generated from message lorenzo.plan.v1.MsgSetMerkleRootResponse
 */
export const MsgSetMerkleRootResponse = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgSetMerkleRootResponse",
  [],
);

/**
 * MsgClaims is the request type for the Msg/Claims RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgClaims
 */
export const MsgClaims = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgClaims",
  () => [
    { no: 1, name: "plan_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "receiver", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "round_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "merkle_proof", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgClaimsResponse is the response type for the Msg/Claims RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgClaimsResponse
 */
export const MsgClaimsResponse = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgClaimsResponse",
  [],
);

/**
 * MsgUpdatePlanStatus is the request type for the Msg/UpdatePlanStatus RPC
 * method.
 *
 * @generated from message lorenzo.plan.v1.MsgUpdatePlanStatus
 */
export const MsgUpdatePlanStatus = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgUpdatePlanStatus",
  () => [
    { no: 1, name: "plan_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "status", kind: "enum", T: proto3.getEnumType(PlanStatus) },
    { no: 3, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgUpdatePlanStatusResponse is the response type for the Msg/UpdatePlanStatus
 * RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgUpdatePlanStatusResponse
 */
export const MsgUpdatePlanStatusResponse = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgUpdatePlanStatusResponse",
  [],
);

/**
 * MsgCreateYAT is the request type for the Msg/CreateYAT RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgCreateYAT
 */
export const MsgCreateYAT = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgCreateYAT",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "symbol", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgCreateYATResponse is the response type for the Msg/CreateYAT RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgCreateYATResponse
 */
export const MsgCreateYATResponse = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgCreateYATResponse",
  () => [
    { no: 1, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgSetMinter is the request type for the Msg/SetMinter RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgSetMinter
 */
export const MsgSetMinter = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgSetMinter",
  () => [
    { no: 1, name: "minter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgSetMinterResponse is the response type for the Msg/SetMinter RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgSetMinterResponse
 */
export const MsgSetMinterResponse = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgSetMinterResponse",
  [],
);

/**
 * MsgRemoveMinter is the request type for the Msg/RemoveMinter RPC method.
 *
 * @generated from message lorenzo.plan.v1.MsgRemoveMinter
 */
export const MsgRemoveMinter = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgRemoveMinter",
  () => [
    { no: 1, name: "minter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "sender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MsgRemoveMinterResponse is the response type for the Msg/RemoveMinter RPC
 * method.
 *
 * @generated from message lorenzo.plan.v1.MsgRemoveMinterResponse
 */
export const MsgRemoveMinterResponse = proto3.makeMessageType(
  "lorenzo.plan.v1.MsgRemoveMinterResponse",
  [],
);

