// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: lorenzo/token/v1/genesis.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { TokenPair } from "./token";

/** GenesisState defines the token module's genesis state. */
export interface GenesisState {
  params?: Params | undefined;
  token_pairs: TokenPair[];
}

/** Params defines the token module parameters. */
export interface Params {
  enable_conversion: boolean;
  enable_evm_hook: boolean;
}

function createBaseGenesisState(): GenesisState {
  return { params: undefined, token_pairs: [] };
}

export const GenesisState = {
  encode(message: GenesisState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).ldelim();
    }
    for (const v of message.token_pairs) {
      TokenPair.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.token_pairs.push(TokenPair.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      token_pairs: globalThis.Array.isArray(object?.token_pairs)
        ? object.token_pairs.map((e: any) => TokenPair.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.token_pairs?.length) {
      obj.token_pairs = message.token_pairs.map((e) => TokenPair.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.token_pairs = object.token_pairs?.map((e) => TokenPair.fromPartial(e)) || [];
    return message;
  },
};

function createBaseParams(): Params {
  return { enable_conversion: false, enable_evm_hook: false };
}

export const Params = {
  encode(message: Params, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.enable_conversion !== false) {
      writer.uint32(8).bool(message.enable_conversion);
    }
    if (message.enable_evm_hook !== false) {
      writer.uint32(16).bool(message.enable_evm_hook);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Params {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.enable_conversion = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.enable_evm_hook = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      enable_conversion: isSet(object.enable_conversion) ? globalThis.Boolean(object.enable_conversion) : false,
      enable_evm_hook: isSet(object.enable_evm_hook) ? globalThis.Boolean(object.enable_evm_hook) : false,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.enable_conversion !== false) {
      obj.enable_conversion = message.enable_conversion;
    }
    if (message.enable_evm_hook !== false) {
      obj.enable_evm_hook = message.enable_evm_hook;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.enable_conversion = object.enable_conversion ?? false;
    message.enable_evm_hook = object.enable_evm_hook ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
