// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/token/v1/token.proto (package lorenzo.token.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Source defines the source type of token asset, if source is:
 * - module: token origin is sdk module;
 * - contract: token origin is erc20 contract;
 *
 * @generated from enum lorenzo.token.v1.Source
 */
export const Source = proto3.makeEnum(
  "lorenzo.token.v1.Source",
  [
    {no: 0, name: "OWNER_UNDEFINED"},
    {no: 1, name: "OWNER_MODULE"},
    {no: 2, name: "OWNER_CONTRACT"},
  ],
);

/**
 * TokenPair defines a pairing of a cosmos coin and an erc20 token
 *
 * @generated from message lorenzo.token.v1.TokenPair
 */
export const TokenPair = proto3.makeMessageType(
  "lorenzo.token.v1.TokenPair",
  () => [
    { no: 1, name: "contract_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "source", kind: "enum", T: proto3.getEnumType(Source) },
  ],
);

