// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/btclightclient/v1/event.proto (package lorenzo.btclightclient.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { BTCHeaderInfo } from "./btclightclient_pb.js";

/**
 * The header included in the event is the block in the history
 * of the current mainchain to which we are rolling back to.
 * In other words, there is one rollback event emitted per re-org, to the
 * greatest common ancestor of the old and the new fork.
 *
 * @generated from message lorenzo.btclightclient.v1.EventBTCRollBack
 */
export declare class EventBTCRollBack extends Message<EventBTCRollBack> {
  /**
   * @generated from field: lorenzo.btclightclient.v1.BTCHeaderInfo header = 1;
   */
  header?: BTCHeaderInfo;

  constructor(data?: PartialMessage<EventBTCRollBack>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.EventBTCRollBack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventBTCRollBack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventBTCRollBack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventBTCRollBack;

  static equals(a: EventBTCRollBack | PlainMessage<EventBTCRollBack> | undefined, b: EventBTCRollBack | PlainMessage<EventBTCRollBack> | undefined): boolean;
}

/**
 * EventBTCRollForward is emitted on Msg/InsertHeader
 * The header included in the event is the one the main chain is extended with.
 * In the event of a reorg, each block on the new fork that comes after
 * the greatest common ancestor will have a corresponding roll forward event.
 *
 * @generated from message lorenzo.btclightclient.v1.EventBTCRollForward
 */
export declare class EventBTCRollForward extends Message<EventBTCRollForward> {
  /**
   * @generated from field: lorenzo.btclightclient.v1.BTCHeaderInfo header = 1;
   */
  header?: BTCHeaderInfo;

  constructor(data?: PartialMessage<EventBTCRollForward>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.EventBTCRollForward";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventBTCRollForward;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventBTCRollForward;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventBTCRollForward;

  static equals(a: EventBTCRollForward | PlainMessage<EventBTCRollForward> | undefined, b: EventBTCRollForward | PlainMessage<EventBTCRollForward> | undefined): boolean;
}

/**
 * EventBTCHeaderInserted is emitted on Msg/InsertHeader
 * The header included in the event is the one that was added to the
 * on chain BTC storage.
 *
 * @generated from message lorenzo.btclightclient.v1.EventBTCHeaderInserted
 */
export declare class EventBTCHeaderInserted extends Message<EventBTCHeaderInserted> {
  /**
   * @generated from field: lorenzo.btclightclient.v1.BTCHeaderInfo header = 1;
   */
  header?: BTCHeaderInfo;

  constructor(data?: PartialMessage<EventBTCHeaderInserted>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.EventBTCHeaderInserted";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventBTCHeaderInserted;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventBTCHeaderInserted;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventBTCHeaderInserted;

  static equals(a: EventBTCHeaderInserted | PlainMessage<EventBTCHeaderInserted> | undefined, b: EventBTCHeaderInserted | PlainMessage<EventBTCHeaderInserted> | undefined): boolean;
}

/**
 * @generated from message lorenzo.btclightclient.v1.EventBTCFeeRateUpdated
 */
export declare class EventBTCFeeRateUpdated extends Message<EventBTCFeeRateUpdated> {
  /**
   * @generated from field: uint64 fee_rate = 1;
   */
  feeRate: bigint;

  constructor(data?: PartialMessage<EventBTCFeeRateUpdated>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.EventBTCFeeRateUpdated";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EventBTCFeeRateUpdated;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EventBTCFeeRateUpdated;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EventBTCFeeRateUpdated;

  static equals(a: EventBTCFeeRateUpdated | PlainMessage<EventBTCFeeRateUpdated> | undefined, b: EventBTCFeeRateUpdated | PlainMessage<EventBTCFeeRateUpdated> | undefined): boolean;
}

