// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/btclightclient/v1/genesis.proto (package lorenzo.btclightclient.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { BTCHeaderInfo } from "./btclightclient_pb.js";

/**
 * GenesisState defines the btclightclient module's genesis state.
 *
 * @generated from message lorenzo.btclightclient.v1.GenesisState
 */
export const GenesisState = proto3.makeMessageType(
  "lorenzo.btclightclient.v1.GenesisState",
  () => [
    { no: 1, name: "params", kind: "message", T: Params },
    { no: 2, name: "base_btc_header", kind: "message", T: BTCHeaderInfo },
  ],
);

