// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/btclightclient/v1/tx.proto (package lorenzo.btclightclient.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";

/**
 * MsgInsertHeaders defines the message for multiple incoming header bytes
 *
 * @generated from message lorenzo.btclightclient.v1.MsgInsertHeaders
 */
export const MsgInsertHeaders = proto3.makeMessageType(
  "lorenzo.btclightclient.v1.MsgInsertHeaders",
  () => [
    { no: 1, name: "signer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "headers", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
  ],
);

/**
 * MsgInsertHeadersResponse defines the response for the InsertHeaders
 * transaction
 *
 * @generated from message lorenzo.btclightclient.v1.MsgInsertHeadersResponse
 */
export const MsgInsertHeadersResponse = proto3.makeMessageType(
  "lorenzo.btclightclient.v1.MsgInsertHeadersResponse",
  [],
);

/**
 * MsgUpdateParams defines a message for updating btc light client module
 * parameters.
 *
 * @generated from message lorenzo.btclightclient.v1.MsgUpdateParams
 */
export const MsgUpdateParams = proto3.makeMessageType(
  "lorenzo.btclightclient.v1.MsgUpdateParams",
  () => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "params", kind: "message", T: Params },
  ],
);

/**
 * MsgUpdateParamsResponse is the response to the MsgUpdateParams message.
 *
 * @generated from message lorenzo.btclightclient.v1.MsgUpdateParamsResponse
 */
export const MsgUpdateParamsResponse = proto3.makeMessageType(
  "lorenzo.btclightclient.v1.MsgUpdateParamsResponse",
  [],
);

/**
 * @generated from message lorenzo.btclightclient.v1.MsgUpdateFeeRate
 */
export const MsgUpdateFeeRate = proto3.makeMessageType(
  "lorenzo.btclightclient.v1.MsgUpdateFeeRate",
  () => [
    { no: 1, name: "signer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "fee_rate", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * @generated from message lorenzo.btclightclient.v1.MsgUpdateFeeRateResponse
 */
export const MsgUpdateFeeRateResponse = proto3.makeMessageType(
  "lorenzo.btclightclient.v1.MsgUpdateFeeRateResponse",
  [],
);

