// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/btclightclient/v1/tx.proto (package lorenzo.btclightclient.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Params } from "./params_pb.js";

/**
 * MsgInsertHeaders defines the message for multiple incoming header bytes
 *
 * @generated from message lorenzo.btclightclient.v1.MsgInsertHeaders
 */
export declare class MsgInsertHeaders extends Message<MsgInsertHeaders> {
  /**
   * @generated from field: string signer = 1;
   */
  signer: string;

  /**
   * @generated from field: repeated bytes headers = 2;
   */
  headers: Uint8Array[];

  constructor(data?: PartialMessage<MsgInsertHeaders>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.MsgInsertHeaders";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgInsertHeaders;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgInsertHeaders;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgInsertHeaders;

  static equals(a: MsgInsertHeaders | PlainMessage<MsgInsertHeaders> | undefined, b: MsgInsertHeaders | PlainMessage<MsgInsertHeaders> | undefined): boolean;
}

/**
 * MsgInsertHeadersResponse defines the response for the InsertHeaders
 * transaction
 *
 * @generated from message lorenzo.btclightclient.v1.MsgInsertHeadersResponse
 */
export declare class MsgInsertHeadersResponse extends Message<MsgInsertHeadersResponse> {
  constructor(data?: PartialMessage<MsgInsertHeadersResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.MsgInsertHeadersResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgInsertHeadersResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgInsertHeadersResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgInsertHeadersResponse;

  static equals(a: MsgInsertHeadersResponse | PlainMessage<MsgInsertHeadersResponse> | undefined, b: MsgInsertHeadersResponse | PlainMessage<MsgInsertHeadersResponse> | undefined): boolean;
}

/**
 * MsgUpdateParams defines a message for updating btc light client module
 * parameters.
 *
 * @generated from message lorenzo.btclightclient.v1.MsgUpdateParams
 */
export declare class MsgUpdateParams extends Message<MsgUpdateParams> {
  /**
   * authority is the address of the governance account.
   * just FYI: cosmos.AddressString marks that this field should use type alias
   * for AddressString instead of string, but the functionality is not yet
   * implemented in cosmos-proto
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * params defines the btc light client parameters to update.
   *
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: lorenzo.btclightclient.v1.Params params = 2;
   */
  params?: Params;

  constructor(data?: PartialMessage<MsgUpdateParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.MsgUpdateParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParams;

  static equals(a: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined, b: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined): boolean;
}

/**
 * MsgUpdateParamsResponse is the response to the MsgUpdateParams message.
 *
 * @generated from message lorenzo.btclightclient.v1.MsgUpdateParamsResponse
 */
export declare class MsgUpdateParamsResponse extends Message<MsgUpdateParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateParamsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.MsgUpdateParamsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParamsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse;

  static equals(a: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined, b: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined): boolean;
}

/**
 * @generated from message lorenzo.btclightclient.v1.MsgUpdateFeeRate
 */
export declare class MsgUpdateFeeRate extends Message<MsgUpdateFeeRate> {
  /**
   * @generated from field: string signer = 1;
   */
  signer: string;

  /**
   * sat/vbyte * 1000
   *
   * @generated from field: uint64 fee_rate = 2;
   */
  feeRate: bigint;

  constructor(data?: PartialMessage<MsgUpdateFeeRate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.MsgUpdateFeeRate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateFeeRate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateFeeRate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateFeeRate;

  static equals(a: MsgUpdateFeeRate | PlainMessage<MsgUpdateFeeRate> | undefined, b: MsgUpdateFeeRate | PlainMessage<MsgUpdateFeeRate> | undefined): boolean;
}

/**
 * @generated from message lorenzo.btclightclient.v1.MsgUpdateFeeRateResponse
 */
export declare class MsgUpdateFeeRateResponse extends Message<MsgUpdateFeeRateResponse> {
  constructor(data?: PartialMessage<MsgUpdateFeeRateResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btclightclient.v1.MsgUpdateFeeRateResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateFeeRateResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateFeeRateResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateFeeRateResponse;

  static equals(a: MsgUpdateFeeRateResponse | PlainMessage<MsgUpdateFeeRateResponse> | undefined, b: MsgUpdateFeeRateResponse | PlainMessage<MsgUpdateFeeRateResponse> | undefined): boolean;
}

