// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/agent/v1/agent.proto (package lorenzo.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Agent defines the details of a project
 *
 * @generated from message lorenzo.agent.v1.Agent
 */
export declare class Agent extends Message<Agent> {
  /**
   * id is the unique identifier of the agent
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * agent name,required
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * btc_receiving_address is agent’s fund escrow address,required
   *
   * @generated from field: string btc_receiving_address = 3;
   */
  btcReceivingAddress: string;

  /**
   * like 0xBAb28FF7659481F1c8516f616A576339936AFB06
   *
   * @generated from field: string eth_addr = 4;
   */
  ethAddr: string;

  /**
   * description is a brief description of the agent, optional
   *
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * url is the agent's link, used for detailed introduction, optional
   *
   * @generated from field: string url = 6;
   */
  url: string;

  constructor(data?: PartialMessage<Agent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.Agent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Agent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Agent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Agent;

  static equals(a: Agent | PlainMessage<Agent> | undefined, b: Agent | PlainMessage<Agent> | undefined): boolean;
}

