// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/agent/v1/params.proto (package lorenzo.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Params defines the parameters for the agent module.
 *
 * @generated from message lorenzo.agent.v1.Params
 */
export declare class Params extends Message<Params> {
  /**
   * List of addresses that are allowed to manage agents.
   *
   * @generated from field: repeated string allow_list = 1;
   */
  allowList: string[];

  constructor(data?: PartialMessage<Params>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.Params";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params;

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean;
}

