// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/agent/v1/query.proto (package lorenzo.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination_pb.js";
import { Agent } from "./agent_pb.js";

/**
 * QueryParamsRequest is the request type for the Query/Params RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryParamsRequest
 */
export const QueryParamsRequest = proto3.makeMessageType(
  "lorenzo.agent.v1.QueryParamsRequest",
  [],
);

/**
 * QueryParamsResponse is the response type for the Query/Params RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryParamsResponse
 */
export const QueryParamsResponse = proto3.makeMessageType(
  "lorenzo.agent.v1.QueryParamsResponse",
  () => [
    { no: 1, name: "params", kind: "message", T: Params },
  ],
);

/**
 * QueryAgentsRequest is the request type for the Query/Agents RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryAgentsRequest
 */
export const QueryAgentsRequest = proto3.makeMessageType(
  "lorenzo.agent.v1.QueryAgentsRequest",
  () => [
    { no: 1, name: "pagination", kind: "message", T: PageRequest },
  ],
);

/**
 * QueryAgentsResponse is the response type for the Query/Agents RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryAgentsResponse
 */
export const QueryAgentsResponse = proto3.makeMessageType(
  "lorenzo.agent.v1.QueryAgentsResponse",
  () => [
    { no: 1, name: "agents", kind: "message", T: Agent, repeated: true },
    { no: 2, name: "pagination", kind: "message", T: PageResponse },
  ],
);

/**
 * QueryAgentRequest is the request type for the Query/Agent RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryAgentRequest
 */
export const QueryAgentRequest = proto3.makeMessageType(
  "lorenzo.agent.v1.QueryAgentRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
);

/**
 * QueryAgentResponse is the response type for the Query/Agent RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryAgentResponse
 */
export const QueryAgentResponse = proto3.makeMessageType(
  "lorenzo.agent.v1.QueryAgentResponse",
  () => [
    { no: 1, name: "agent", kind: "message", T: Agent },
  ],
);

