// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/agent/v1/query.proto (package lorenzo.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Params } from "./params_pb.js";
import type { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination_pb.js";
import type { Agent } from "./agent_pb.js";

/**
 * QueryParamsRequest is the request type for the Query/Params RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryParamsRequest
 */
export declare class QueryParamsRequest extends Message<QueryParamsRequest> {
  constructor(data?: PartialMessage<QueryParamsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.QueryParamsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsRequest;

  static equals(a: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined, b: QueryParamsRequest | PlainMessage<QueryParamsRequest> | undefined): boolean;
}

/**
 * QueryParamsResponse is the response type for the Query/Params RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryParamsResponse
 */
export declare class QueryParamsResponse extends Message<QueryParamsResponse> {
  /**
   * params holds all the parameters of this module.
   *
   * @generated from field: lorenzo.agent.v1.Params params = 1;
   */
  params?: Params;

  constructor(data?: PartialMessage<QueryParamsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.QueryParamsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryParamsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryParamsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryParamsResponse;

  static equals(a: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined, b: QueryParamsResponse | PlainMessage<QueryParamsResponse> | undefined): boolean;
}

/**
 * QueryAgentsRequest is the request type for the Query/Agents RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryAgentsRequest
 */
export declare class QueryAgentsRequest extends Message<QueryAgentsRequest> {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;

  constructor(data?: PartialMessage<QueryAgentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.QueryAgentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAgentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAgentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAgentsRequest;

  static equals(a: QueryAgentsRequest | PlainMessage<QueryAgentsRequest> | undefined, b: QueryAgentsRequest | PlainMessage<QueryAgentsRequest> | undefined): boolean;
}

/**
 * QueryAgentsResponse is the response type for the Query/Agents RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryAgentsResponse
 */
export declare class QueryAgentsResponse extends Message<QueryAgentsResponse> {
  /**
   * Agent Contains the details of the agent.
   *
   * @generated from field: repeated lorenzo.agent.v1.Agent agents = 1;
   */
  agents: Agent[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;

  constructor(data?: PartialMessage<QueryAgentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.QueryAgentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAgentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAgentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAgentsResponse;

  static equals(a: QueryAgentsResponse | PlainMessage<QueryAgentsResponse> | undefined, b: QueryAgentsResponse | PlainMessage<QueryAgentsResponse> | undefined): boolean;
}

/**
 * QueryAgentRequest is the request type for the Query/Agent RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryAgentRequest
 */
export declare class QueryAgentRequest extends Message<QueryAgentRequest> {
  /**
   * id is the unique identifier of the agent
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<QueryAgentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.QueryAgentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAgentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAgentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAgentRequest;

  static equals(a: QueryAgentRequest | PlainMessage<QueryAgentRequest> | undefined, b: QueryAgentRequest | PlainMessage<QueryAgentRequest> | undefined): boolean;
}

/**
 * QueryAgentResponse is the response type for the Query/Agent RPC method.
 *
 * @generated from message lorenzo.agent.v1.QueryAgentResponse
 */
export declare class QueryAgentResponse extends Message<QueryAgentResponse> {
  /**
   * Agent Contains the details of the agent.
   *
   * @generated from field: lorenzo.agent.v1.Agent agent = 1;
   */
  agent?: Agent;

  constructor(data?: PartialMessage<QueryAgentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.QueryAgentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): QueryAgentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): QueryAgentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): QueryAgentResponse;

  static equals(a: QueryAgentResponse | PlainMessage<QueryAgentResponse> | undefined, b: QueryAgentResponse | PlainMessage<QueryAgentResponse> | undefined): boolean;
}

