// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/agent/v1/tx.proto (package lorenzo.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Params } from "./params_pb.js";

/**
 * @generated from message lorenzo.agent.v1.MsgUpdateParams
 */
export declare class MsgUpdateParams extends Message<MsgUpdateParams> {
  /**
   * authority is the address of the governance account.
   * just FYI: cosmos.AddressString marks that this field should use type alias
   * for AddressString instead of string, but the functionality is not yet
   * implemented in cosmos-proto
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: lorenzo.agent.v1.Params params = 2;
   */
  params?: Params;

  constructor(data?: PartialMessage<MsgUpdateParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.MsgUpdateParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParams;

  static equals(a: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined, b: MsgUpdateParams | PlainMessage<MsgUpdateParams> | undefined): boolean;
}

/**
 * MsgUpdateParamsResponse is the response to the MsgUpdateParams message.
 *
 * @generated from message lorenzo.agent.v1.MsgUpdateParamsResponse
 */
export declare class MsgUpdateParamsResponse extends Message<MsgUpdateParamsResponse> {
  constructor(data?: PartialMessage<MsgUpdateParamsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.MsgUpdateParamsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateParamsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateParamsResponse;

  static equals(a: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined, b: MsgUpdateParamsResponse | PlainMessage<MsgUpdateParamsResponse> | undefined): boolean;
}

/**
 * MsgUpdateParams defines a message for add a agent.
 *
 * @generated from message lorenzo.agent.v1.MsgAddAgent
 */
export declare class MsgAddAgent extends Message<MsgAddAgent> {
  /**
   * agent name,required
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * btc_receiving_address is agent’s fund escrow address,required
   *
   * @generated from field: string btc_receiving_address = 2;
   */
  btcReceivingAddress: string;

  /**
   * like 0xBAb28FF7659481F1c8516f616A576339936AFB06
   *
   * @generated from field: string eth_addr = 3;
   */
  ethAddr: string;

  /**
   * description is a brief description of the agent, optional
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * url is the agent's link, used for detailed introduction, optional
   *
   * @generated from field: string url = 5;
   */
  url: string;

  /**
   * sender is the address of the governance account or module admin
   *
   * @generated from field: string sender = 6;
   */
  sender: string;

  constructor(data?: PartialMessage<MsgAddAgent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.MsgAddAgent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddAgent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddAgent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddAgent;

  static equals(a: MsgAddAgent | PlainMessage<MsgAddAgent> | undefined, b: MsgAddAgent | PlainMessage<MsgAddAgent> | undefined): boolean;
}

/**
 * MsgAddAgentResponse is the response to the MsgAddAgent message.
 *
 * @generated from message lorenzo.agent.v1.MsgAddAgentResponse
 */
export declare class MsgAddAgentResponse extends Message<MsgAddAgentResponse> {
  /**
   * id is the unique identifier of the agent
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<MsgAddAgentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.MsgAddAgentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgAddAgentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgAddAgentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgAddAgentResponse;

  static equals(a: MsgAddAgentResponse | PlainMessage<MsgAddAgentResponse> | undefined, b: MsgAddAgentResponse | PlainMessage<MsgAddAgentResponse> | undefined): boolean;
}

/**
 * MsgEditAgent defines a message for editting the agent.
 *
 * @generated from message lorenzo.agent.v1.MsgEditAgent
 */
export declare class MsgEditAgent extends Message<MsgEditAgent> {
  /**
   * id is the unique identifier of the agent
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * agent name,required
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * description is a brief description of the agent, optional
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * url is the agent's link, used for detailed introduction, optional
   *
   * @generated from field: string url = 4;
   */
  url: string;

  /**
   * sender is the address of the governance account or module admin
   *
   * @generated from field: string sender = 5;
   */
  sender: string;

  constructor(data?: PartialMessage<MsgEditAgent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.MsgEditAgent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgEditAgent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgEditAgent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgEditAgent;

  static equals(a: MsgEditAgent | PlainMessage<MsgEditAgent> | undefined, b: MsgEditAgent | PlainMessage<MsgEditAgent> | undefined): boolean;
}

/**
 * MsgEditAgentResponse is the response to the MsgEditAgent message.
 *
 * @generated from message lorenzo.agent.v1.MsgEditAgentResponse
 */
export declare class MsgEditAgentResponse extends Message<MsgEditAgentResponse> {
  constructor(data?: PartialMessage<MsgEditAgentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.MsgEditAgentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgEditAgentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgEditAgentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgEditAgentResponse;

  static equals(a: MsgEditAgentResponse | PlainMessage<MsgEditAgentResponse> | undefined, b: MsgEditAgentResponse | PlainMessage<MsgEditAgentResponse> | undefined): boolean;
}

/**
 * MsgRemoveAgent defines a message for removing the agent.
 *
 * @generated from message lorenzo.agent.v1.MsgRemoveAgent
 */
export declare class MsgRemoveAgent extends Message<MsgRemoveAgent> {
  /**
   * id is the unique identifier of the agent
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * sender is the address of the governance account or module admin
   *
   * @generated from field: string sender = 2;
   */
  sender: string;

  constructor(data?: PartialMessage<MsgRemoveAgent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.MsgRemoveAgent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRemoveAgent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRemoveAgent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRemoveAgent;

  static equals(a: MsgRemoveAgent | PlainMessage<MsgRemoveAgent> | undefined, b: MsgRemoveAgent | PlainMessage<MsgRemoveAgent> | undefined): boolean;
}

/**
 * MsgRemoveAgentResponse is the response to the MsgRemoveAgent message.
 *
 * @generated from message lorenzo.agent.v1.MsgRemoveAgentResponse
 */
export declare class MsgRemoveAgentResponse extends Message<MsgRemoveAgentResponse> {
  constructor(data?: PartialMessage<MsgRemoveAgentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.agent.v1.MsgRemoveAgentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgRemoveAgentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgRemoveAgentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgRemoveAgentResponse;

  static equals(a: MsgRemoveAgentResponse | PlainMessage<MsgRemoveAgentResponse> | undefined, b: MsgRemoveAgentResponse | PlainMessage<MsgRemoveAgentResponse> | undefined): boolean;
}

