// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/btcstaking/v1/event.proto (package lorenzo.btcstaking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { BTCStakingRecord } from "./staking_record_pb.js";
import { Coin } from "../../../cosmos/base/v1beta1/coin_pb.js";

/**
 * BTC staking creation event
 *
 * @generated from message lorenzo.btcstaking.v1.EventBTCStakingCreated
 */
export const EventBTCStakingCreated = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.EventBTCStakingCreated",
  () => [
    { no: 1, name: "record", kind: "message", T: BTCStakingRecord },
  ],
);

/**
 * @generated from message lorenzo.btcstaking.v1.EventBurnCreated
 */
export const EventBurnCreated = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.EventBurnCreated",
  () => [
    { no: 1, name: "signer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "btc_target_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount", kind: "message", T: Coin },
  ],
);

