// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/btcstaking/v1/genesis.proto (package lorenzo.btcstaking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";

/**
 * GenesisState defines the btcstaking module's genesis state.
 *
 * @generated from message lorenzo.btcstaking.v1.GenesisState
 */
export const GenesisState = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.GenesisState",
  () => [
    { no: 1, name: "params", kind: "message", T: Params },
  ],
);

