// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/btcstaking/v1/params.proto (package lorenzo.btcstaking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message lorenzo.btcstaking.v1.Receiver
 */
export const Receiver = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.Receiver",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "addr", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "eth_addr", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * GenesisState defines the btcstaking module's genesis state.
 *
 * @generated from message lorenzo.btcstaking.v1.Params
 */
export const Params = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.Params",
  () => [
    { no: 1, name: "receivers", kind: "message", T: Receiver, repeated: true },
    { no: 2, name: "btc_confirmations_depth", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "minter_allow_list", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "bridge_addr", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "txout_dust_amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

