// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/btcstaking/v1/query.proto (package lorenzo.btcstaking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { BTCStakingRecord } from "./staking_record_pb.js";

/**
 * @generated from message lorenzo.btcstaking.v1.QueryParamsRequest
 */
export const QueryParamsRequest = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.QueryParamsRequest",
  [],
);

/**
 * @generated from message lorenzo.btcstaking.v1.QueryParamsResponse
 */
export const QueryParamsResponse = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.QueryParamsResponse",
  () => [
    { no: 1, name: "params", kind: "message", T: Params },
  ],
);

/**
 * @generated from message lorenzo.btcstaking.v1.StakingRecordDisplay
 */
export const StakingRecordDisplay = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.StakingRecordDisplay",
  () => [
    { no: 1, name: "tx_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "receiver_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "agent_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "agent_btc_addr", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "chain_id", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

/**
 * @generated from message lorenzo.btcstaking.v1.QueryStakingRecordRequest
 */
export const QueryStakingRecordRequest = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.QueryStakingRecordRequest",
  () => [
    { no: 1, name: "txHash", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message lorenzo.btcstaking.v1.QueryStakingRecordResponse
 */
export const QueryStakingRecordResponse = proto3.makeMessageType(
  "lorenzo.btcstaking.v1.QueryStakingRecordResponse",
  () => [
    { no: 1, name: "record", kind: "message", T: BTCStakingRecord },
  ],
);

