// @generated by protoc-gen-es v1.0.0
// @generated from file lorenzo/btcstaking/v1/staking_record.proto (package lorenzo.btcstaking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message lorenzo.btcstaking.v1.BTCStakingRecord
 */
export declare class BTCStakingRecord extends Message<BTCStakingRecord> {
  /**
   * @generated from field: bytes tx_hash = 1;
   */
  txHash: Uint8Array;

  /**
   * @generated from field: uint64 amount = 2;
   */
  amount: bigint;

  /**
   * @generated from field: bytes receiver_addr = 3;
   */
  receiverAddr: Uint8Array;

  /**
   * @generated from field: string agent_name = 4;
   */
  agentName: string;

  /**
   * @generated from field: string agent_btc_addr = 5;
   */
  agentBtcAddr: string;

  /**
   * @generated from field: uint32 chain_id = 6;
   */
  chainId: number;

  /**
   * @generated from field: string mint_yat_result = 7;
   */
  mintYatResult: string;

  constructor(data?: PartialMessage<BTCStakingRecord>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "lorenzo.btcstaking.v1.BTCStakingRecord";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BTCStakingRecord;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BTCStakingRecord;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BTCStakingRecord;

  static equals(a: BTCStakingRecord | PlainMessage<BTCStakingRecord> | undefined, b: BTCStakingRecord | PlainMessage<BTCStakingRecord> | undefined): boolean;
}

